authors:
  Joe:
    name: Jiho Bak
    description: AI Engineer
    avatar: https://imagedelivery.net/IEMzXmjRvW0g933AN5ejrA/assetsbulletsofiles-1e3505fb-58e4-808f-a46b-c3b3d62721e5-attachment38a2708a-4f4b-4129-a39e-770aa397015cmepng/format=auto,w=256